---
apiVersion: v1
kind: pack
spec:
  name: performance-metrics
  queries:
  - description: Records the CPU time and memory usage for each individual query.
      Helpful for identifying queries that may impact performance.
    interval: 0
    name: Per_Query_Perf
    query: Per_Query_Perf
    snapshot: true
  - description: Track the amount of CPU time used by osquery.
    interval: 0
    name: Runtime_Perf
    query: Runtime_Perf
    snapshot: true
  - description: Track the percentage of total CPU time utilized by $endpoint_security_tool
    interval: 0
    name: Endpoint_Security_Tool_Perf
    query: Endpoint_Security_Tool_Perf
    snapshot: true
  - description: Track the percentage of total CPU time utilized by $backup_tool
    interval: 0
    name: Backup_Tool_Perf
    query: Backup_Tool_Perf
    snapshot: true
  targets:
    labels: null
---
apiVersion: v1
kind: query
spec:
  description: Records the CPU time and memory usage for each individual query. Helpful
    for identifying queries that may impact performance.
  name: Per_Query_Perf
  query: SELECT name, interval, executions, output_size, wall_time, (user_time/executions)
    AS avg_user_time, (system_time/executions) AS avg_system_time, average_memory
    FROM osquery_schedule;
---
apiVersion: v1
kind: query
spec:
  description: Track the amount of CPU time used by osquery.
  name: Runtime_Perf
  query: SELECT ov.version AS os_version, ov.platform AS os_platform, ov.codename
    AS os_codename, i.*, p.resident_size, p.user_time, p.system_time, time.minutes
    AS counter, db.db_size_mb AS database_size FROM osquery_info i, os_version ov,
    processes p, time, (SELECT (sum(size) / 1024) / 1024.0 AS db_size_mb FROM (SELECT
    value FROM osquery_flags WHERE name = 'database_path' LIMIT 1) flags, file WHERE
    path LIKE flags.value || '%%' AND type = 'regular') db WHERE p.pid = i.pid;
---
apiVersion: v1
kind: query
spec:
  description: Track the percentage of total CPU time utilized by $endpoint_security_tool
  name: Endpoint_Security_Tool_Perf
  query: SELECT ((tool_time*100)/(SUM(system_time) + SUM(user_time))) AS pct FROM
    processes, (SELECT (SUM(processes.system_time)+SUM(processes.user_time)) AS tool_time
    FROM processes WHERE name='endpoint_security_tool');
---
apiVersion: v1
kind: query
spec:
  description: Track the percentage of total CPU time utilized by $backup_tool
  name: Backup_Tool_Perf
  query: SELECT ((backuptool_time*100)/(SUM(system_time) + SUM(user_time))) AS pct
    FROM processes, (SELECT (SUM(processes.system_time)+SUM(processes.user_time))
    AS backuptool_time FROM processes WHERE name='backup_tool');
