---
apiVersion: v1
kind: pack
spec:
  name: windows-attacks
  queries:
  - description: 'Searches for the presence of the ''Debugger'' registry key for common
      Windows accessibility tools. More info: (https://blogs.technet.microsoft.com/jonathantrull/2016/10/03/detecting-sticky-key-backdoors/)'
    interval: 0
    name: StickyKeys_Registry_Backdoor
    query: StickyKeys_Registry_Backdoor
    version: 2.2.1
  - description: Detect processes masquerading as legitimate Windows processes
    interval: 0
    name: svchost.exe_incorrect_parent_process
    query: svchost.exe_incorrect_parent_process
    version: 2.2.1
  - description: (https://sensorstechforum.com/ccleaner-trojan-floxif-malware-how-to-remove/)
    interval: 3600
    name: CCleaner_Trojan.Floxif
    query: CCleaner_Trojan.Floxif
    version: 2.2.1
  - description: (https://sensorstechforum.com/untabs-browser-extension-virus-remove-completely/)
    interval: 3600
    name: unTabs_2
    query: unTabs_2
    version: 2.2.1
  - description: (https://sensorstechforum.com/untabs-browser-extension-virus-remove-completely/)
    interval: 3600
    name: unTabs_1
    query: unTabs_1
    version: 2.2.1
  - description: Detect processes masquerading as legitimate Windows processes
    interval: 0
    name: conhost.exe_incorrect_path
    query: conhost.exe_incorrect_path
    version: 2.2.1
  - description: Detect processes masquerading as legitimate Windows processes
    interval: 0
    name: dllhost.exe_incorrect_path
    query: dllhost.exe_incorrect_path
    version: 2.2.1
  - description: (https://sensorstechforum.com/ccleaner-trojan-floxif-malware-how-to-remove/)
    interval: 3600
    name: CCleaner_Trojan_stage2.Floxif
    query: CCleaner_Trojan_stage2.Floxif
    version: 2.1.0
  - description: (https://sensorstechforum.com/windows-infected-2-viruses-scam-remove/)
    interval: 3600
    name: Winsecurity_info_2
    query: Winsecurity_info_2
    version: 2.2.1
  - description: Detect processes masquerading as legitimate Windows processes
    interval: 0
    name: lsass.exe_incorrect_path
    query: lsass.exe_incorrect_path
    version: 2.2.1
  - description: Detect processes masquerading as legitimate Windows processes
    interval: 0
    name: svchost.exe_incorrect_path
    query: svchost.exe_incorrect_path
    version: 2.2.1
  - description: Detect processes masquerading as legitimate Windows processes
    interval: 0
    name: services.exe_incorrect_parent_process
    query: services.exe_incorrect_parent_process
    version: 2.2.1
  - description: (https://sensorstechforum.com/windows-infected-2-viruses-scam-remove/)
    interval: 3600
    name: Winsecurity_info_1
    query: Winsecurity_info_1
    version: 2.2.1
  - description: 'Checks the hashes of accessibility tools to ensure they don''t match
      the hashes of cmd.exe, powershell.exe, or explorer.exe. More info: (https://github.com/TrullJ/sticky-keys-scanner/blob/master/TestFor-StickyKey.ps1)'
    interval: 0
    name: StickyKeys_File_Replace_Backdoor
    query: StickyKeys_File_Replace_Backdoor
    version: 2.2.1
  targets:
    labels: null
---
apiVersion: v1
kind: query
spec:
  description: 'Searches for the presence of the ''Debugger'' registry key for common
    Windows accessibility tools. More info: (https://blogs.technet.microsoft.com/jonathantrull/2016/10/03/detecting-sticky-key-backdoors/)'
  name: StickyKeys_Registry_Backdoor
  query: SELECT * FROM registry WHERE key LIKE 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows
    NT\CurrentVersion\Image File Execution Options\%%' and name='Debugger';
---
apiVersion: v1
kind: query
spec:
  description: Detect processes masquerading as legitimate Windows processes
  name: svchost.exe_incorrect_parent_process
  query: SELECT name FROM processes WHERE pid=(SELECT parent FROM processes WHERE
    LOWER(name)='svchost.exe') AND LOWER(name)!='services.exe';
---
apiVersion: v1
kind: query
spec:
  description: (https://sensorstechforum.com/ccleaner-trojan-floxif-malware-how-to-remove/)
  name: CCleaner_Trojan.Floxif
  query: select * from registry where path like 'HKEY_LOCAL_MACHINE\SOFTWARE\Piriform\Agomo%';
---
apiVersion: v1
kind: query
spec:
  description: (https://sensorstechforum.com/untabs-browser-extension-virus-remove-completely/)
  name: unTabs_2
  query: select * from chrome_extensions join users using (uid) where name like 'unTabs%';
---
apiVersion: v1
kind: query
spec:
  description: (https://sensorstechforum.com/untabs-browser-extension-virus-remove-completely/)
  name: unTabs_1
  query: select * from programs where name like 'unTabs%';
---
apiVersion: v1
kind: query
spec:
  description: Detect processes masquerading as legitimate Windows processes
  name: conhost.exe_incorrect_path
  query: SELECT * FROM processes WHERE LOWER(name)='conhost.exe' AND LOWER(path)!='c:\windows\system32\conhost.exe'
    AND path!='';
---
apiVersion: v1
kind: query
spec:
  description: Detect processes masquerading as legitimate Windows processes
  name: dllhost.exe_incorrect_path
  query: SELECT * FROM processes WHERE LOWER(name)='dllhost.exe' AND LOWER(path)!='c:\windows\system32\dllhost.exe'
    AND LOWER(path)!='c:\windows\syswow64\dllhost.exe' AND path!='';
---
apiVersion: v1
kind: query
spec:
  description: (https://sensorstechforum.com/ccleaner-trojan-floxif-malware-how-to-remove/)
  name: CCleaner_Trojan_stage2.Floxif
  query: select h.md5, h.sha1, h.sha256, s.name, s.service_type, s.display_name, s.module_path,
    s.user_account from services s, hash h where h.path = s.module_path and ((s.module_path
    like '%GeeSetup_x86%' and h.sha256 = 'dc9b5e8aa6ec86db8af0a7aa897ca61db3e5f3d2e0942e319074db1aaccfdc83')
    or (s.module_path like '%EFACli64%' and h.sha256 = '128aca58be325174f0220bd7ca6030e4e206b4378796e82da460055733bb6f4f')
    or (s.module_path like '%TSMSISrv%' and h.sha256 = '07fb252d2e853a9b1b32f30ede411f2efbb9f01e4a7782db5eacf3f55cf34902'));
---
apiVersion: v1
kind: query
spec:
  description: (https://sensorstechforum.com/windows-infected-2-viruses-scam-remove/)
  name: Winsecurity_info_2
  query: select * from chrome_extensions join users using (uid) where name = 'Winsecurity.info';
---
apiVersion: v1
kind: query
spec:
  description: Detect processes masquerading as legitimate Windows processes
  name: lsass.exe_incorrect_path
  query: SELECT * FROM processes WHERE LOWER(name)='lsass.exe' AND LOWER(path)!='c:\windows\system32\lsass.exe'
    AND path!='';
---
apiVersion: v1
kind: query
spec:
  description: Detect processes masquerading as legitimate Windows processes
  name: svchost.exe_incorrect_path
  query: SELECT * FROM processes WHERE LOWER(name)='svchost.exe' AND LOWER(path)!='c:\windows\system32\svchost.exe'
    AND LOWER(path)!='c:\windows\syswow64\svchost.exe' AND path!='';
---
apiVersion: v1
kind: query
spec:
  description: Detect processes masquerading as legitimate Windows processes
  name: services.exe_incorrect_parent_process
  query: SELECT name FROM processes WHERE pid=(SELECT parent FROM processes WHERE
    LOWER(name)='services.exe') AND LOWER(name)!='wininit.exe';
---
apiVersion: v1
kind: query
spec:
  description: (https://sensorstechforum.com/windows-infected-2-viruses-scam-remove/)
  name: Winsecurity_info_1
  query: select * from programs where name = 'Winsecurity.info';
---
apiVersion: v1
kind: query
spec:
  description: 'Checks the hashes of accessibility tools to ensure they don''t match
    the hashes of cmd.exe, powershell.exe, or explorer.exe. More info: (https://github.com/TrullJ/sticky-keys-scanner/blob/master/TestFor-StickyKey.ps1)'
  name: StickyKeys_File_Replace_Backdoor
  query: SELECT * FROM hash WHERE (path='c:\windows\system32\osk.exe' OR path='c:\windows\system32\sethc.exe'
    OR path='c:\windows\system32\narrator.exe' OR path='c:\windows\system32\magnify.exe'
    OR path='c:\windows\system32\displayswitch.exe') AND sha256 IN (SELECT sha256
    FROM hash WHERE path='c:\windows\system32\cmd.exe' OR path='c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
    OR path='c:\windows\system32\explorer.exe') AND sha256!='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
